name: FINE
channels:
  - nodefaults
dependencies:
  - conda-forge::python>=3.10
  - conda-forge::libiconv
  - conda-forge::gdal=3.4
  - conda-forge::geopandas
  - conda-forge::jupyter
  - conda-forge::notebook
  - conda-forge::libpysal
  - conda-forge::pip
  - conda-forge::descartes
  - conda-forge::glpk
  - conda-forge::openpyxl
  - conda-forge::matplotlib
  - conda-forge::xlrd
  - conda-forge::pyomo
  - conda-forge::numpy
  - conda-forge::pandas>=2
  - conda-forge::networkx
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::xarray
  - conda-forge::rasterio
  - conda-forge::netcdf4
  - conda-forge::tsam

  - pip:
      - .
