name: FINE
dependencies:
- python
- conda-forge::libiconv
- conda-forge::gdal=2.4.1
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- conda-forge::libpysal
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd==1.2.0
- pyomo
- numpy
- pandas
- GPyOpt
- networkx
- scipy
- pwlf
- pyDOE
- sphinx_rtd_theme
- scikit-learn
- xarray
- seaborn
- conda-forge::rasterio
- conda-forge::netcdf4

- pip:
    - tsam
