name: Check code formatting and Linter hints

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["develop"]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
          version: "0.13.1"
      - name: Check Linter
        run: ruff check --output-format=github --config=pyproject.toml
      - name: Check Format
        run: ruff format --diff --config=pyproject.toml
