name: Check code formatting and Linter hints

on: [ push ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Check Linter
        run: ruff check --output-format=github . --config pyproject.toml fine
    # Needs to be activated to resolve issue https://github.com/FZJ-IEK3-VSA/FINE/issues/100
    #   - name: Check Format
    #     run: ruff format --check --config pyproject.toml