name: Check code formatting and Linter hints

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["develop"]

jobs:
  ruff:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    uses: FZJ-IEK3-VSA/.github/.github/workflows/lint.yml@v1
    with:
      ruff_version: "0.13.1"
