on:
  workflow_dispatch:
  pull_request:
    branches: ["develop"]

jobs:
  TestPullCondaForgeDev:
    name: Test development version on ${{ matrix.runner_tag }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python_version: ["3.10", "3.13"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements_dev.yml
      ipynb_example_folder: "examples"
      library_name: "python"
      library_version: ${{ matrix.python_version }}
      dependency_position_env_file: "0"
  TestPullPyPIDev:
    name: Test PyPI development version on ${{ matrix.runner_tag }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["ubuntu-latest", "macos-latest", "windows-latest"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_pypi_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      ipynb_example_folder: "examples"
      python_version: "3.13"
      optional_dependency_PyPI_tag: "[develop]"
      additional_conda_forge_dependencies: "glpk"
  TestMinDependencies:
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
        dependencies:
          [
            { library_name: python, version: 3.10.0, yaml_position: 0 },
            { library_name: geopandas, version: 1.0.0, yaml_position: 2 },
            { library_name: glpk, version: 4.63, yaml_position: 3 },
            { library_name: xlrd, version: 1.2.0, yaml_position: 6 },
            { library_name: pyomo, version: 6.8, yaml_position: 7 },
            { library_name: numpy, version: 1.22.0, yaml_position: 8 },
            { library_name: pandas, version: 1.4.0, yaml_position: 9 },
            { library_name: scipy, version: 1.7.2, yaml_position: 10 },
            { library_name: scikit-learn, version: 1.2.0, yaml_position: 11 },
            { library_name: xarray, version: 2022.3.0, yaml_position: 12 },
            { library_name: rasterio, version: 1.3.7, yaml_position: 13 },
            { library_name: netcdf4, version: 1.6.4, yaml_position: 14 },
            { library_name: tsam, version: 2.0.1, yaml_position: 15 },
            { library_name: pwlf, version: 2.0.4, yaml_position: 16 },
            { library_name: psutil, version: 5.8.0, yaml_position: 17 },
            {
              library_name: gurobi-logtools,
              version: 3.0.0,
              yaml_position: 18,
            },
          ]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements_dev.yml
      ipynb_example_folder: "examples"
      library_name: ${{ matrix.dependencies.library_name }}
      library_version: ${{ matrix.dependencies.version }}
      dependency_position_env_file: ${{ matrix.dependencies.yaml_position }}
