on:
  push:
    branches: ["**"]

jobs:
  TestPushCondaForgeDev:
    name: Test conda-forge development version on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: test_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba env create --name test_env --yes --file requirements_dev.yml
          mamba run --name test_env pip install . --no-deps
          echo "Installation done"
          mamba list --name test_env
          echo "libaries printed"
          echo "start pytest"
          mamba run --name test_env pytest -vv
          echo "Pytest done"
      - name: Run Examples Conda Forge
        shell: pwsh
        run: |
            mamba run --name test_env python -m pytest -n auto --dist loadscope --nbval-lax --nbval-current-env  --durations=20 examples/

  TestPushPyPIDev:
    name: Test PyPi development version on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: test_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba env create --name test_env python=3.10 glpk
          echo "Python and glpk installation is done"
          mamba list --name test_env
          echo "Print dependencies from conda forge before installing pypi dependencies"
          mamba run --name test_env pip install .[develop]
          echo "pip installation is done"
          pip list -v
          echo "All dependencies are shown"
          echo "libaries printed"
          echo "start pytest"
          mamba run --name test_env pytest -vv
          echo "Pytest done"
      - name: Run Examples PyPI
        shell: pwsh
        run: |
            mamba run --name test_env python -m pytest -n auto --dist loadscope --nbval-lax --nbval-current-env  --durations=20 examples/

