on:
  push:
    branches: ["70_add_ci"]


jobs:
  TestPushCondaForgeDev:
    name: Test conda-forge development version on ${{ matrix.os }} for numpy=${{ matrix.numpy_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted"]
        numpy_version: ["2.3","2.2","2.1","2.0","1.26","1.25","1.24","1.23","1.22","1.21","1.20"]
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
      - name: Checkout
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: 25.3.0-3
          channels: conda-forge
          activate-environment: ""
          conda-remove-defaults: "true"
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'requirements_dev.yml'
          commitChange: false
          method: CreateOrUpdate
          # The number in the brackets needs behind at "dependencies[...]" needs to ab adjusted when dependencies are
          # added or removed. It represents the position of the dependency in the "requirements-dev.yml" file starting
          # with the first dependency as "0".
          changes: |
            {
            "dependencies[8]": "numpy =${{ matrix.numpy_version }}"
            }
      - name: Setup environment
        shell: pwsh
        run: |
            get-content requirements_dev.yml
            ls
            echo "LS Done"
            mamba env create --name test_env --yes --file requirements_dev.yml
            mamba run --name test_env pip install -e . --no-deps
            echo "Installation done"
            mamba list --name test_env
            echo "packages printed"
      - name: Run tests
        shell: pwsh
        run: |
          echo "start pytest"
          mamba run --name test_env pytest -n auto  -vv
          echo "Pytest done"
      - name: Run Examples Conda Forge
        shell: pwsh
        run: |
            mamba run --name test_env python -m pytest -n auto --dist loadscope --nbval-lax --nbval-current-env  --durations=20 examples/

  TestPushPyPIDev:
    name: Test PyPi development version on ${{ matrix.os }} for numpy=${{ matrix.numpy_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted"]        
        numpy_version: ["2.3","2.2","2.1","2.0","1.26","1.25","1.24","1.23","1.22","1.21","1.20"]
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
      - name: Checkout
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: 25.3.0-3
          channels: conda-forge
          activate-environment: test_env
          conda-remove-defaults: "true"
      - name: Setup Envionment
        shell: pwsh
        run: |
            ls
            echo "LS Done"
            mamba env create --name test_env numpy=${{ matrix.numpy_version }} glpk
            echo "Python and glpk installation is done"
            mamba list --name test_env
            echo "Print dependencies from conda forge before installing pypi dependencies"
            mamba run --name test_env pip install .[develop]
            echo "pip installation is done"
            pip list -v
            echo "All dependencies are shown"
      - name: Run Pytest
        shell: pwsh
        run: 
          echo "start pytest"
          mamba run --name test_env pytest -n auto  -vv
          echo "Pytest done"
      - name: Run Examples PyPI
        shell: pwsh
        run: |
            mamba run --name test_env python -m pytest -n auto --dist loadscope --nbval-lax --nbval-current-env  --durations=20 examples/

