on:
  workflow_dispatch:
  push:
    branches: ["485_test_dependency_range_new_release"]
  pull_request:
    branches: ["master"]

jobs:
  TestPushCondaForgeDev:
    name: Test conda-forge development version on ${{ matrix.runner_tag }} for scipy=${{ matrix.scipy_version }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
        scipy_version:
          [
            "1.7.2",
            "1.7.3",
            "1.8.0",
            "1.8.1",
            "1.9.0",
            "1.9.1",
            "1.9.2",
            "1.9.3",
            "1.10.0",
            "1.10.1",
            "1.11.0",
            "1.11.1",
            "1.11.2",
            "1.11.3",
            "1.11.4",
            "1.12.0",
            "1.13.0",
            "1.13.1",
            "1.14.0",
            "1.14.1",
            "1.15.0",
            "1.15.1",
            "1.15.2",
            "1.16.0",
            "1.16.1",
            "1.16.2",
          ]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements_dev.yml
      ipynb_example_folder: "examples"
      library_name: "scipy"
      library_version: ${{ matrix.scipy_version }}
      dependency_position_env_file: "10"

  # We decided not to test old dependency ranges on PyPI as there are many known incompatabilities
  # of indirect dependencies. There is no method known to us to automatically test, store share this information
  # TestPushPyPIDev:
  #   name: Test PyPi development version on ${{ matrix.runner_tag }} for numpy=${{ matrix.scipy_version }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       runner_tag: ["self-hosted"]
  #       # scipy_version: ["2.3","2.2","2.1","2.0","1.26","1.25","1.24","1.23","1.22"]
  #       scipy_version: ["2.3","2.2"]
  #   uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_pypi_test.yml@main
  #   with:
  #       runner_tag: ${{ matrix.runner_tag }}
  #       ipynb_example_folder: "examples"
  #       python_version: "3.13"
  #       optional_dependency_PyPI_tag: "[develop]"
  #       additional_conda_forge_dependencies: "glpk"
  #       library_name: "numpy"
  #       library_version: ${{ matrix.scipy_version }}
