on:
  push:
    branches: ["70_add_ci"]
  pull_request:
    branches: ["master"]

jobs:
  TestPushCondaForgeDev:
    name: Test conda-forge development version on ${{ matrix.os }} for numpy=${{ matrix.numpy_version }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
        numpy_version: ["2.3","2.2","2.1","2.0","1.26","1.25","1.24","1.23","1.22"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
        runner_tag: ${{ matrix.runner_tag }}
        requirements_file_name: requirements_dev.yml
        ipynb_example_folder: "examples"
        library_name: "numpy"
        library_version: ${{ matrix.numpy_version }}
        dependency_position_env_file: "8"
  TestPushPyPIDev:
    name: Test PyPi development version on ${{ matrix.os }} for numpy=${{ matrix.numpy_version }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]        
        # numpy_version: ["2.3","2.2","2.1","2.0","1.26","1.25","1.24","1.23","1.22"]
        numpy_version: ["2.3","2.2"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_pypi_test.yml@main
    with:
        runner_tag: ${{ matrix.runner_tag }}
        ipynb_example_folder: "examples"
        python_version: "3.13"
        optional_dependency_PyPI_tag: "[develop]"
        additional_conda_forge_dependencies: "glpk"
        library_name: "numpy"
        library_version: ${{ matrix.numpy_version }}

